### ISSUE TITLE
got this error, please help

### ISSUE THREAD

**Issue by b-e-e** [afollestad/drag-select-recyclerview#11]
java.lang.NoSuchFieldError: No static field abc_ic_ab_back_mtrl_am_alpha of type I in class Lcom/afollestad/materialcab/R$drawable; or its superclasses (declaration of 'com.afollestad.materialcab.R$drawable' appears in /data/app/com.afollestad.dragselectrecyclerviewsample-1/base.apk)
            at com.afollestad.materialcab.MaterialCab.reset(MaterialCab.java:88)
            at com.afollestad.materialcab.MaterialCab.<init>(MaterialCab.java:67)
            at com.afollestad.dragselectrecyclerviewsample.MainActivity.onDragSelectionChanged(MainActivity.java:69)
            at com.afollestad.dragselectrecyclerview.DragSelectRecyclerViewAdapter.fireSelectionListener(DragSelectRecyclerViewAdapter.java:28)
            at com.afollestad.dragselectrecyclerview.DragSelectRecyclerViewAdapter.toggleSelected(DragSelectRecyclerViewAdapter.java:85)
            at com.afollestad.dragselectrecyclerviewsample.MainActivity.onClick(MainActivity.java:57)
            at com.afollestad.dragselectrecyclerviewsample.MainAdapter$MainViewHolder.onClick(MainAdapter.java:122)
            at android.view.View.performClick(View.java:5198)
            at android.view.View$PerformClick.run(View.java:21147)
            at android.os.Handler.handleCallback(Handler.java:739)
            at android.os.Handler.dispatchMessage(Handler.java:95)
            at android.os.Looper.loop(Looper.java:148)
            at android.app.ActivityThread.main(ActivityThread.java:5417)
            at java.lang.reflect.Method.invoke(Native Method)
            at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
            at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)

**Comment by afollestad** [comment]
Upgrade to a newer version of the library
